name: prebuild

on:
  release:
    types:
      - published

env:
  ELECTRON_BUILD_CMD: npx --no-install prebuild -r electron -t 29.0.0 --include-regex 'better_sqlite3.node$' -u ${{ secrets.GITHUB_TOKEN }}

jobs:
  prebuild:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - macos-latest
          - macos-14
          - windows-2019
    name: Prebuild on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - if: ${{ startsWith(matrix.os, 'windows') }}
        run: pip.exe install setuptools
      - if: ${{ ! startsWith(matrix.os, 'windows') && matrix.os != 'macos-14' }}
        run: python3 -m pip install --break-system-packages setuptools
      - if: matrix.os == 'macos-14'
        run: python3 -m pip install --break-system-packages setuptools
      - run: npm install --ignore-scripts
      - run: ${{ env.ELECTRON_BUILD_CMD }}
      - if: matrix.os == 'windows-2019'
        run: |
          ${{ env.ELECTRON_BUILD_CMD }} --arch ia32
          ${{ env.ELECTRON_BUILD_CMD }} --arch arm64

  prebuild-alpine-linux:
    name: Prebuild on Alpine-Linux (x64)
    runs-on: ubuntu-latest
    container: node:16-alpine
    steps:
      - uses: actions/checkout@v4
      - run: apk add build-base git python3 py3-setuptools --update-cache
      - run: npm install --ignore-scripts
      - run: ${{ env.ELECTRON_BUILD_CMD }}

  prebuild-alpine-linux-arm64:
    name: Prebuild on Alpine-Linux (arm64)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - run: |
          docker run --rm -v $(pwd):/tmp/project --entrypoint /bin/sh --platform linux/arm64 node:16-alpine -c "\
          apk add build-base git python3 py3-setuptools --update-cache && \
          cd /tmp/project && \
          npm install --ignore-scripts && \
          ${{ env.ELECTRON_BUILD_CMD }}"

  prebuild-linux-arm:
    strategy:
      fail-fast: false
      matrix:
        arch:
          - arm/v7
          - arm64
    name: Prebuild on Linux (${{ matrix.arch }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - run: |
          docker run --rm -v $(pwd):/tmp/project --entrypoint /bin/sh --platform linux/${{ matrix.arch }} node:16 -c "\
          cd /tmp/project && \
          npm install --ignore-scripts && \
          ${{ env.ELECTRON_BUILD_CMD }}"
