name: windows-arm64-test

on:
  workflow_dispatch:

jobs:
  prebuild-node:
    name: Prebuild for Node on Windows (arm64)
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - run: pip.exe install setuptools
      - run: npm install --ignore-scripts
      - run: npx --no-install prebuild -r node -t 20.0.0 --include-regex 'better_sqlite3.node$' --arch arm64

  prebuild-electron:
    name: Prebuild for Electron on Windows (arm64)
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - run: pip.exe install setuptools
      - run: npm install --ignore-scripts
      - run: npx --no-install prebuild -r electron -t 16.0.0 -t 17.0.0 -t 18.0.0 -t 19.0.0 -t 20.0.0 -t 21.0.0 -t 22.0.0 -t 23.0.0 -t 24.0.0 -t 25.0.0 -t 26.0.0 -t 27.0.0 -t 28.0.0 --include-regex 'better_sqlite3.node$' --arch arm64